"""
Historical top 50 most popular domains by year (2000-2025).

Compiled from multiple sources including:
- Hosting.com historical rankings (1995-2023)
- Visual Capitalist web traffic data (1993-2022)
- Cloudflare Radar Year in Review (2020-2023)
- comScore Media Metrix top 50 US web properties (2006-2010)
- Similarweb / Semrush top websites rankings (2022-2025)
- Proxidize top 100 most popular websites (2025)
- TIME Magazine 50 Best Websites annual lists (2006-2014)
- Alexa Internet historical rankings (2003-2022)
- Wikipedia: List of most-visited websites

Each year contains 50 domains reflecting the actual popular sites of that era,
including sites that may now be defunct, acquired, or available for registration.
"""

DOMAINS_BY_YEAR = {

    # =========================================================================
    # 2000: AOL dominance, dot-com bubble peak, web portals, early e-commerce
    # =========================================================================
    2000: [
        "aol.com",
        "yahoo.com",
        "msn.com",
        "ebay.com",
        "amazon.com",
        "lycos.com",
        "about.com",
        "excite.com",
        "altavista.com",
        "geocities.com",
        "go.com",
        "netscape.com",
        "napster.com",
        "hotmail.com",
        "angelfire.com",
        "tripod.com",
        "ask.com",
        "bbc.co.uk",
        "cnn.com",
        "cnet.com",
        "americangreetings.com",
        "mapquest.com",
        "weather.com",
        "realplayer.com",
        "real.com",
        "iwon.com",
        "bolt.com",
        "homestead.com",
        "bluemountain.com",
        "deja.com",
        "goto.com",
        "dogpile.com",
        "hotbot.com",
        "nbci.com",
        "snap.com",
        "zdnet.com",
        "salon.com",
        "slate.com",
        "nytimes.com",
        "washingtonpost.com",
        "imdb.com",
        "priceline.com",
        "expedia.com",
        "etrade.com",
        "mp3.com",
        "download.com",
        "tucows.com",
        "icq.com",
        "evite.com",
        "classmates.com",
    ],

    # =========================================================================
    # 2001: Dot-com bust, Google rising, Wikipedia launches, Napster lawsuit
    # =========================================================================
    2001: [
        "yahoo.com",
        "aol.com",
        "msn.com",
        "ebay.com",
        "google.com",
        "amazon.com",
        "bbc.co.uk",
        "lycos.com",
        "about.com",
        "cnet.com",
        "excite.com",
        "altavista.com",
        "geocities.com",
        "ask.com",
        "netscape.com",
        "hotmail.com",
        "weather.com",
        "mapquest.com",
        "imdb.com",
        "cnn.com",
        "angelfire.com",
        "tripod.com",
        "nytimes.com",
        "zdnet.com",
        "kazaa.com",
        "napster.com",
        "download.com",
        "priceline.com",
        "expedia.com",
        "overture.com",
        "go.com",
        "salon.com",
        "dogpile.com",
        "metacrawler.com",
        "real.com",
        "americangreetings.com",
        "homestead.com",
        "bluemountain.com",
        "deja.com",
        "bolt.com",
        "wikipedia.org",
        "classmates.com",
        "icq.com",
        "tucows.com",
        "evite.com",
        "iwon.com",
        "slashdot.org",
        "sourceforge.net",
        "hotbot.com",
        "snap.com",
    ],

    # =========================================================================
    # 2002: Google gains ground, Yahoo still #1, Friendster launches
    # =========================================================================
    2002: [
        "yahoo.com",
        "msn.com",
        "aol.com",
        "google.com",
        "ebay.com",
        "amazon.com",
        "bbc.co.uk",
        "ask.com",
        "about.com",
        "lycos.com",
        "cnet.com",
        "weather.com",
        "mapquest.com",
        "cnn.com",
        "imdb.com",
        "geocities.com",
        "kazaa.com",
        "altavista.com",
        "excite.com",
        "hotmail.com",
        "nytimes.com",
        "craigslist.org",
        "friendster.com",
        "download.com",
        "zdnet.com",
        "overture.com",
        "realplayer.com",
        "priceline.com",
        "expedia.com",
        "angelfire.com",
        "tripod.com",
        "classmates.com",
        "go.com",
        "netscape.com",
        "slashdot.org",
        "sourceforge.net",
        "salon.com",
        "washingtonpost.com",
        "dogpile.com",
        "metacrawler.com",
        "wikipedia.org",
        "homestead.com",
        "tucows.com",
        "icq.com",
        "bolt.com",
        "livejournal.com",
        "blogger.com",
        "walmart.com",
        "evite.com",
        "real.com",
    ],

    # =========================================================================
    # 2003: Google climbing, Kazaa top search, MySpace launches, LinkedIn starts
    # =========================================================================
    2003: [
        "yahoo.com",
        "msn.com",
        "google.com",
        "aol.com",
        "ebay.com",
        "amazon.com",
        "ask.com",
        "bbc.co.uk",
        "walmart.com",
        "cnet.com",
        "weather.com",
        "mapquest.com",
        "cnn.com",
        "about.com",
        "imdb.com",
        "craigslist.org",
        "kazaa.com",
        "lycos.com",
        "geocities.com",
        "altavista.com",
        "hotmail.com",
        "nytimes.com",
        "friendster.com",
        "download.com",
        "overture.com",
        "classmates.com",
        "linkedin.com",
        "myspace.com",
        "livejournal.com",
        "blogger.com",
        "wikipedia.org",
        "zdnet.com",
        "slashdot.org",
        "sourceforge.net",
        "priceline.com",
        "expedia.com",
        "orbitz.com",
        "salon.com",
        "washingtonpost.com",
        "realplayer.com",
        "netscape.com",
        "tripod.com",
        "angelfire.com",
        "dogpile.com",
        "excite.com",
        "go.com",
        "tucows.com",
        "icq.com",
        "xanga.com",
        "bolt.com",
    ],

    # =========================================================================
    # 2004: MySpace grows, Facebook launches, Flickr launches, Gmail debuts
    # =========================================================================
    2004: [
        "yahoo.com",
        "msn.com",
        "google.com",
        "aol.com",
        "ebay.com",
        "amazon.com",
        "ask.com",
        "bbc.co.uk",
        "walmart.com",
        "weather.com",
        "cnet.com",
        "mapquest.com",
        "cnn.com",
        "about.com",
        "imdb.com",
        "craigslist.org",
        "myspace.com",
        "wikipedia.org",
        "friendster.com",
        "facebook.com",
        "flickr.com",
        "gmail.com",
        "livejournal.com",
        "blogger.com",
        "nytimes.com",
        "download.com",
        "classmates.com",
        "linkedin.com",
        "kazaa.com",
        "lycos.com",
        "geocities.com",
        "xanga.com",
        "zdnet.com",
        "slashdot.org",
        "sourceforge.net",
        "hotmail.com",
        "altavista.com",
        "priceline.com",
        "expedia.com",
        "orbitz.com",
        "overture.com",
        "salon.com",
        "dogpile.com",
        "excite.com",
        "realplayer.com",
        "netscape.com",
        "tripod.com",
        "angelfire.com",
        "digg.com",
        "typepad.com",
    ],

    # =========================================================================
    # 2005: YouTube launches, MySpace peaks, Reddit launches, Web 2.0 era
    # =========================================================================
    2005: [
        "yahoo.com",
        "google.com",
        "msn.com",
        "aol.com",
        "ebay.com",
        "amazon.com",
        "ask.com",
        "bbc.co.uk",
        "myspace.com",
        "walmart.com",
        "weather.com",
        "cnet.com",
        "mapquest.com",
        "cnn.com",
        "about.com",
        "wikipedia.org",
        "craigslist.org",
        "imdb.com",
        "youtube.com",
        "flickr.com",
        "facebook.com",
        "livejournal.com",
        "blogger.com",
        "nytimes.com",
        "reddit.com",
        "linkedin.com",
        "friendster.com",
        "download.com",
        "classmates.com",
        "digg.com",
        "xanga.com",
        "deviantart.com",
        "newgrounds.com",
        "miniclip.com",
        "addictinggames.com",
        "hotmail.com",
        "geocities.com",
        "lycos.com",
        "zdnet.com",
        "slashdot.org",
        "sourceforge.net",
        "priceline.com",
        "expedia.com",
        "orbitz.com",
        "kazaa.com",
        "salon.com",
        "typepad.com",
        "bebo.com",
        "stumbleupon.com",
        "photobucket.com",
    ],

    # =========================================================================
    # 2006: Google takes #1, YouTube acquired, MySpace #3, Twitter launches
    # =========================================================================
    2006: [
        "google.com",
        "yahoo.com",
        "msn.com",
        "myspace.com",
        "ebay.com",
        "aol.com",
        "ask.com",
        "amazon.com",
        "bbc.co.uk",
        "wikipedia.org",
        "youtube.com",
        "facebook.com",
        "craigslist.org",
        "weather.com",
        "cnn.com",
        "walmart.com",
        "cnet.com",
        "mapquest.com",
        "about.com",
        "imdb.com",
        "nytimes.com",
        "flickr.com",
        "blogger.com",
        "digg.com",
        "reddit.com",
        "linkedin.com",
        "twitter.com",
        "deviantart.com",
        "photobucket.com",
        "livejournal.com",
        "stumbleupon.com",
        "friendster.com",
        "bebo.com",
        "xanga.com",
        "classmates.com",
        "miniclip.com",
        "newgrounds.com",
        "addictinggames.com",
        "hi5.com",
        "badoo.com",
        "technorati.com",
        "del.icio.us",
        "sourceforge.net",
        "slashdot.org",
        "priceline.com",
        "expedia.com",
        "download.com",
        "kongregate.com",
        "tagged.com",
        "metacafe.com",
    ],

    # =========================================================================
    # 2007: MySpace still big, Facebook surging, iPhone launches, Tumblr starts
    # =========================================================================
    2007: [
        "google.com",
        "yahoo.com",
        "msn.com",
        "myspace.com",
        "ebay.com",
        "ask.com",
        "aol.com",
        "amazon.com",
        "bbc.co.uk",
        "wikipedia.org",
        "youtube.com",
        "facebook.com",
        "craigslist.org",
        "cnn.com",
        "weather.com",
        "walmart.com",
        "cnet.com",
        "about.com",
        "imdb.com",
        "nytimes.com",
        "flickr.com",
        "digg.com",
        "twitter.com",
        "linkedin.com",
        "blogger.com",
        "reddit.com",
        "photobucket.com",
        "stumbleupon.com",
        "deviantart.com",
        "mapquest.com",
        "livejournal.com",
        "bebo.com",
        "hi5.com",
        "friendster.com",
        "tagged.com",
        "badoo.com",
        "tumblr.com",
        "metacafe.com",
        "hulu.com",
        "technorati.com",
        "del.icio.us",
        "miniclip.com",
        "newgrounds.com",
        "kongregate.com",
        "sourceforge.net",
        "xanga.com",
        "classmates.com",
        "priceline.com",
        "expedia.com",
        "addictinggames.com",
    ],

    # =========================================================================
    # 2008: Google dominant, Facebook overtakes MySpace, YouTube explodes
    # =========================================================================
    2008: [
        "google.com",
        "yahoo.com",
        "youtube.com",
        "facebook.com",
        "msn.com",
        "ask.com",
        "amazon.com",
        "myspace.com",
        "yandex.ru",
        "bbc.co.uk",
        "wikipedia.org",
        "ebay.com",
        "craigslist.org",
        "cnn.com",
        "weather.com",
        "aol.com",
        "walmart.com",
        "imdb.com",
        "twitter.com",
        "linkedin.com",
        "digg.com",
        "flickr.com",
        "hulu.com",
        "cnet.com",
        "about.com",
        "nytimes.com",
        "blogger.com",
        "reddit.com",
        "photobucket.com",
        "stumbleupon.com",
        "tumblr.com",
        "deviantart.com",
        "hi5.com",
        "bebo.com",
        "tagged.com",
        "badoo.com",
        "mapquest.com",
        "metacafe.com",
        "technorati.com",
        "del.icio.us",
        "livejournal.com",
        "sourceforge.net",
        "friendster.com",
        "miniclip.com",
        "newgrounds.com",
        "kongregate.com",
        "addictinggames.com",
        "netflix.com",
        "priceline.com",
        "expedia.com",
    ],

    # =========================================================================
    # 2009: Facebook surpasses MySpace, Twitter mainstream, Hulu grows
    # =========================================================================
    2009: [
        "yahoo.com",
        "google.com",
        "youtube.com",
        "facebook.com",
        "amazon.com",
        "msn.com",
        "ask.com",
        "yandex.ru",
        "wikipedia.org",
        "bbc.co.uk",
        "ebay.com",
        "twitter.com",
        "craigslist.org",
        "cnn.com",
        "weather.com",
        "myspace.com",
        "aol.com",
        "linkedin.com",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "cnet.com",
        "digg.com",
        "netflix.com",
        "flickr.com",
        "tumblr.com",
        "reddit.com",
        "nytimes.com",
        "about.com",
        "blogger.com",
        "photobucket.com",
        "stumbleupon.com",
        "deviantart.com",
        "tagged.com",
        "hi5.com",
        "badoo.com",
        "mapquest.com",
        "yelp.com",
        "metacafe.com",
        "livejournal.com",
        "technorati.com",
        "del.icio.us",
        "sourceforge.net",
        "bebo.com",
        "friendster.com",
        "miniclip.com",
        "priceline.com",
        "expedia.com",
        "kongregate.com",
        "vimeo.com",
    ],

    # =========================================================================
    # 2010: Facebook #2, Instagram/Pinterest launch, Groupon/Foursquare hot
    # =========================================================================
    2010: [
        "yahoo.com",
        "google.com",
        "youtube.com",
        "facebook.com",
        "amazon.com",
        "yandex.ru",
        "msn.com",
        "ask.com",
        "wikipedia.org",
        "baidu.com",
        "ebay.com",
        "twitter.com",
        "craigslist.org",
        "cnn.com",
        "linkedin.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "netflix.com",
        "aol.com",
        "walmart.com",
        "imdb.com",
        "digg.com",
        "tumblr.com",
        "reddit.com",
        "flickr.com",
        "yelp.com",
        "cnet.com",
        "nytimes.com",
        "about.com",
        "blogger.com",
        "deviantart.com",
        "foursquare.com",
        "groupon.com",
        "stumbleupon.com",
        "photobucket.com",
        "pinterest.com",
        "instagram.com",
        "myspace.com",
        "tagged.com",
        "badoo.com",
        "vimeo.com",
        "metacafe.com",
        "mapquest.com",
        "miniclip.com",
        "sourceforge.net",
        "livejournal.com",
        "formspring.me",
        "chatroulette.com",
        "newgrounds.com",
    ],

    # =========================================================================
    # 2011: Google+ launches, Facebook dominant social, Spotify grows
    # =========================================================================
    2011: [
        "google.com",
        "yahoo.com",
        "youtube.com",
        "facebook.com",
        "amazon.com",
        "yandex.ru",
        "wikipedia.org",
        "baidu.com",
        "ask.com",
        "msn.com",
        "ebay.com",
        "twitter.com",
        "linkedin.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "netflix.com",
        "hulu.com",
        "tumblr.com",
        "reddit.com",
        "aol.com",
        "walmart.com",
        "imdb.com",
        "yelp.com",
        "flickr.com",
        "cnet.com",
        "nytimes.com",
        "pinterest.com",
        "instagram.com",
        "about.com",
        "blogger.com",
        "groupon.com",
        "foursquare.com",
        "deviantart.com",
        "stumbleupon.com",
        "spotify.com",
        "plus.google.com",
        "soundcloud.com",
        "digg.com",
        "vimeo.com",
        "photobucket.com",
        "tagged.com",
        "badoo.com",
        "myspace.com",
        "quora.com",
        "mapquest.com",
        "livingsocial.com",
        "formspring.me",
        "dropbox.com",
    ],

    # =========================================================================
    # 2012: Facebook IPO, Instagram acquired, Pinterest explodes
    # =========================================================================
    2012: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "yahoo.com",
        "wikipedia.org",
        "amazon.com",
        "baidu.com",
        "vk.com",
        "yandex.ru",
        "ask.com",
        "ebay.com",
        "twitter.com",
        "linkedin.com",
        "msn.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "netflix.com",
        "tumblr.com",
        "reddit.com",
        "pinterest.com",
        "instagram.com",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "aol.com",
        "yelp.com",
        "cnet.com",
        "nytimes.com",
        "flickr.com",
        "blogger.com",
        "spotify.com",
        "soundcloud.com",
        "about.com",
        "groupon.com",
        "foursquare.com",
        "deviantart.com",
        "stumbleupon.com",
        "plus.google.com",
        "vimeo.com",
        "dropbox.com",
        "digg.com",
        "tagged.com",
        "badoo.com",
        "quora.com",
        "kickstarter.com",
        "etsy.com",
        "myspace.com",
        "livingsocial.com",
    ],

    # =========================================================================
    # 2013: Vine launches, Snapchat grows, Candy Crush era
    # =========================================================================
    2013: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "yahoo.com",
        "wikipedia.org",
        "twitter.com",
        "amazon.com",
        "baidu.com",
        "yandex.ru",
        "vk.com",
        "ebay.com",
        "linkedin.com",
        "msn.com",
        "ask.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "tumblr.com",
        "reddit.com",
        "netflix.com",
        "pinterest.com",
        "instagram.com",
        "weather.com",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "yelp.com",
        "spotify.com",
        "vine.co",
        "snapchat.com",
        "soundcloud.com",
        "cnet.com",
        "nytimes.com",
        "flickr.com",
        "blogger.com",
        "aol.com",
        "about.com",
        "deviantart.com",
        "plus.google.com",
        "vimeo.com",
        "dropbox.com",
        "etsy.com",
        "foursquare.com",
        "kickstarter.com",
        "groupon.com",
        "stumbleupon.com",
        "buzzfeed.com",
        "quora.com",
        "badoo.com",
        "tagged.com",
    ],

    # =========================================================================
    # 2014: Twitch acquired by Amazon, Vine peaks, WhatsApp acquired by Facebook
    # =========================================================================
    2014: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "yahoo.com",
        "wikipedia.org",
        "twitter.com",
        "yandex.ru",
        "amazon.com",
        "baidu.com",
        "vk.com",
        "ebay.com",
        "linkedin.com",
        "msn.com",
        "ask.com",
        "instagram.com",
        "reddit.com",
        "tumblr.com",
        "pinterest.com",
        "netflix.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "yelp.com",
        "spotify.com",
        "vine.co",
        "snapchat.com",
        "twitch.tv",
        "whatsapp.com",
        "soundcloud.com",
        "buzzfeed.com",
        "cnet.com",
        "nytimes.com",
        "vimeo.com",
        "dropbox.com",
        "etsy.com",
        "kickstarter.com",
        "aol.com",
        "blogger.com",
        "deviantart.com",
        "plus.google.com",
        "quora.com",
        "flickr.com",
        "foursquare.com",
        "groupon.com",
        "about.com",
        "badoo.com",
    ],

    # =========================================================================
    # 2015: Instagram booms, Periscope/Meerkat live streaming, Uber/Airbnb growth
    # =========================================================================
    2015: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "yahoo.com",
        "wikipedia.org",
        "twitter.com",
        "baidu.com",
        "instagram.com",
        "yandex.ru",
        "amazon.com",
        "ebay.com",
        "linkedin.com",
        "reddit.com",
        "pinterest.com",
        "tumblr.com",
        "netflix.com",
        "vk.com",
        "msn.com",
        "ask.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "snapchat.com",
        "twitch.tv",
        "vine.co",
        "spotify.com",
        "whatsapp.com",
        "uber.com",
        "airbnb.com",
        "soundcloud.com",
        "buzzfeed.com",
        "yelp.com",
        "etsy.com",
        "vimeo.com",
        "dropbox.com",
        "cnet.com",
        "nytimes.com",
        "periscope.tv",
        "medium.com",
        "quora.com",
        "kickstarter.com",
        "imgur.com",
        "deviantart.com",
        "aol.com",
        "blogger.com",
        "flickr.com",
    ],

    # =========================================================================
    # 2016: TikTok precursor Musical.ly, Snapchat IPO prep, Pokemon Go
    # =========================================================================
    2016: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "yahoo.com",
        "wikipedia.org",
        "baidu.com",
        "twitter.com",
        "instagram.com",
        "yandex.ru",
        "amazon.com",
        "ebay.com",
        "reddit.com",
        "linkedin.com",
        "netflix.com",
        "pinterest.com",
        "tumblr.com",
        "vk.com",
        "msn.com",
        "ask.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "snapchat.com",
        "twitch.tv",
        "hulu.com",
        "walmart.com",
        "imdb.com",
        "spotify.com",
        "whatsapp.com",
        "uber.com",
        "airbnb.com",
        "buzzfeed.com",
        "soundcloud.com",
        "vine.co",
        "yelp.com",
        "etsy.com",
        "dropbox.com",
        "vimeo.com",
        "medium.com",
        "imgur.com",
        "quora.com",
        "cnet.com",
        "nytimes.com",
        "musical.ly",
        "periscope.tv",
        "deviantart.com",
        "kickstarter.com",
        "aol.com",
        "flickr.com",
    ],

    # =========================================================================
    # 2017: Vine dies (Jan), TikTok launches internationally, Facebook dominates
    # =========================================================================
    2017: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "baidu.com",
        "wikipedia.org",
        "yahoo.com",
        "twitter.com",
        "instagram.com",
        "yandex.ru",
        "amazon.com",
        "reddit.com",
        "ebay.com",
        "linkedin.com",
        "netflix.com",
        "pinterest.com",
        "twitch.tv",
        "vk.com",
        "tumblr.com",
        "msn.com",
        "snapchat.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "spotify.com",
        "whatsapp.com",
        "walmart.com",
        "imdb.com",
        "ask.com",
        "buzzfeed.com",
        "uber.com",
        "airbnb.com",
        "soundcloud.com",
        "yelp.com",
        "etsy.com",
        "dropbox.com",
        "medium.com",
        "imgur.com",
        "quora.com",
        "vimeo.com",
        "discord.com",
        "tiktok.com",
        "cnet.com",
        "nytimes.com",
        "deviantart.com",
        "kickstarter.com",
        "fandom.com",
        "github.com",
        "stackoverflow.com",
    ],

    # =========================================================================
    # 2018: TikTok merges with Musical.ly, YouTube #2, Twitter/Instagram grow
    # =========================================================================
    2018: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "baidu.com",
        "wikipedia.org",
        "yahoo.com",
        "twitter.com",
        "instagram.com",
        "yandex.ru",
        "amazon.com",
        "reddit.com",
        "ebay.com",
        "linkedin.com",
        "netflix.com",
        "twitch.tv",
        "pinterest.com",
        "vk.com",
        "tumblr.com",
        "msn.com",
        "tiktok.com",
        "snapchat.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "spotify.com",
        "whatsapp.com",
        "walmart.com",
        "imdb.com",
        "buzzfeed.com",
        "discord.com",
        "uber.com",
        "airbnb.com",
        "yelp.com",
        "etsy.com",
        "dropbox.com",
        "medium.com",
        "imgur.com",
        "quora.com",
        "vimeo.com",
        "soundcloud.com",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "cnet.com",
        "nytimes.com",
        "booking.com",
        "deviantart.com",
        "kickstarter.com",
    ],

    # =========================================================================
    # 2019: TikTok surges, Disney+ launches, Zoom pre-pandemic
    # =========================================================================
    2019: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "baidu.com",
        "wikipedia.org",
        "twitter.com",
        "yahoo.com",
        "instagram.com",
        "yandex.ru",
        "amazon.com",
        "reddit.com",
        "linkedin.com",
        "netflix.com",
        "ebay.com",
        "twitch.tv",
        "tiktok.com",
        "pinterest.com",
        "vk.com",
        "msn.com",
        "snapchat.com",
        "tumblr.com",
        "craigslist.org",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "spotify.com",
        "whatsapp.com",
        "discord.com",
        "walmart.com",
        "imdb.com",
        "disneyplus.com",
        "buzzfeed.com",
        "uber.com",
        "airbnb.com",
        "yelp.com",
        "etsy.com",
        "dropbox.com",
        "medium.com",
        "imgur.com",
        "quora.com",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "zoom.us",
        "vimeo.com",
        "soundcloud.com",
        "booking.com",
        "cnet.com",
        "nytimes.com",
    ],

    # =========================================================================
    # 2020: Pandemic year - Zoom explodes, TikTok surges, Netflix peaks
    # =========================================================================
    2020: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "baidu.com",
        "wikipedia.org",
        "twitter.com",
        "instagram.com",
        "yahoo.com",
        "yandex.ru",
        "amazon.com",
        "tiktok.com",
        "netflix.com",
        "reddit.com",
        "linkedin.com",
        "ebay.com",
        "twitch.tv",
        "zoom.us",
        "microsoft.com",
        "apple.com",
        "msn.com",
        "pinterest.com",
        "vk.com",
        "snapchat.com",
        "whatsapp.com",
        "discord.com",
        "spotify.com",
        "walmart.com",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "hulu.com",
        "disneyplus.com",
        "imdb.com",
        "tumblr.com",
        "craigslist.org",
        "etsy.com",
        "shopify.com",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "quora.com",
        "imgur.com",
        "medium.com",
        "buzzfeed.com",
        "nytimes.com",
        "vimeo.com",
        "roblox.com",
        "houseparty.com",
        "booking.com",
        "uber.com",
    ],

    # =========================================================================
    # 2021: TikTok beats Google (Cloudflare), crypto boom, remote work
    # =========================================================================
    2021: [
        "tiktok.com",
        "google.com",
        "facebook.com",
        "microsoft.com",
        "apple.com",
        "amazon.com",
        "netflix.com",
        "youtube.com",
        "twitter.com",
        "whatsapp.com",
        "instagram.com",
        "baidu.com",
        "wikipedia.org",
        "yahoo.com",
        "yandex.ru",
        "reddit.com",
        "linkedin.com",
        "zoom.us",
        "ebay.com",
        "twitch.tv",
        "snapchat.com",
        "pinterest.com",
        "discord.com",
        "spotify.com",
        "vk.com",
        "msn.com",
        "walmart.com",
        "hulu.com",
        "disneyplus.com",
        "hbomax.com",
        "roblox.com",
        "shopify.com",
        "etsy.com",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "imdb.com",
        "tumblr.com",
        "craigslist.org",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "quora.com",
        "imgur.com",
        "medium.com",
        "telegram.org",
        "signal.org",
        "coinbase.com",
        "nytimes.com",
        "buzzfeed.com",
    ],

    # =========================================================================
    # 2022: ChatGPT launches (Nov), Elon buys Twitter, Mastodon surges briefly
    # =========================================================================
    2022: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "twitter.com",
        "wikipedia.org",
        "reddit.com",
        "instagram.com",
        "baidu.com",
        "yahoo.com",
        "yandex.ru",
        "amazon.com",
        "tiktok.com",
        "whatsapp.com",
        "linkedin.com",
        "netflix.com",
        "ebay.com",
        "twitch.tv",
        "microsoft.com",
        "apple.com",
        "msn.com",
        "vk.com",
        "pinterest.com",
        "snapchat.com",
        "discord.com",
        "spotify.com",
        "zoom.us",
        "walmart.com",
        "hulu.com",
        "disneyplus.com",
        "roblox.com",
        "imdb.com",
        "weather.com",
        "cnn.com",
        "bbc.co.uk",
        "nytimes.com",
        "etsy.com",
        "shopify.com",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "quora.com",
        "imgur.com",
        "medium.com",
        "tumblr.com",
        "telegram.org",
        "openai.com",
        "booking.com",
        "canva.com",
        "mastodon.social",
        "buzzfeed.com",
    ],

    # =========================================================================
    # 2023: ChatGPT/AI boom, Twitter becomes X, Threads launches
    # =========================================================================
    2023: [
        "google.com",
        "facebook.com",
        "youtube.com",
        "instagram.com",
        "twitter.com",
        "baidu.com",
        "wikipedia.org",
        "yahoo.com",
        "yandex.ru",
        "whatsapp.com",
        "amazon.com",
        "tiktok.com",
        "reddit.com",
        "linkedin.com",
        "netflix.com",
        "x.com",
        "chatgpt.com",
        "openai.com",
        "bing.com",
        "ebay.com",
        "twitch.tv",
        "microsoft.com",
        "apple.com",
        "discord.com",
        "snapchat.com",
        "pinterest.com",
        "spotify.com",
        "vk.com",
        "msn.com",
        "walmart.com",
        "disneyplus.com",
        "hulu.com",
        "roblox.com",
        "imdb.com",
        "weather.com",
        "cnn.com",
        "bbc.co.uk",
        "nytimes.com",
        "etsy.com",
        "github.com",
        "stackoverflow.com",
        "fandom.com",
        "quora.com",
        "canva.com",
        "zoom.us",
        "telegram.org",
        "medium.com",
        "booking.com",
        "temu.com",
        "threads.net",
    ],

    # =========================================================================
    # 2024: AI tools proliferate, Temu/Shein e-commerce growth, X decline
    # =========================================================================
    2024: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "instagram.com",
        "x.com",
        "reddit.com",
        "whatsapp.com",
        "wikipedia.org",
        "chatgpt.com",
        "bing.com",
        "yahoo.com",
        "tiktok.com",
        "yandex.ru",
        "amazon.com",
        "baidu.com",
        "linkedin.com",
        "netflix.com",
        "twitch.tv",
        "twitter.com",
        "microsoft.com",
        "apple.com",
        "discord.com",
        "pinterest.com",
        "spotify.com",
        "openai.com",
        "temu.com",
        "snapchat.com",
        "ebay.com",
        "vk.com",
        "canva.com",
        "nytimes.com",
        "cnn.com",
        "bbc.co.uk",
        "weather.com",
        "walmart.com",
        "roblox.com",
        "fandom.com",
        "imdb.com",
        "etsy.com",
        "github.com",
        "zoom.us",
        "telegram.org",
        "booking.com",
        "disneyplus.com",
        "shein.com",
        "quora.com",
        "stackoverflow.com",
        "medium.com",
        "threads.net",
        "perplexity.ai",
    ],

    # =========================================================================
    # 2025: AI dominance, DeepSeek emergence, ChatGPT top 5
    # =========================================================================
    2025: [
        "google.com",
        "youtube.com",
        "facebook.com",
        "instagram.com",
        "chatgpt.com",
        "x.com",
        "reddit.com",
        "whatsapp.com",
        "wikipedia.org",
        "bing.com",
        "yahoo.co.jp",
        "tiktok.com",
        "yahoo.com",
        "yandex.ru",
        "amazon.com",
        "baidu.com",
        "linkedin.com",
        "naver.com",
        "netflix.com",
        "live.com",
        "temu.com",
        "pinterest.com",
        "bilibili.com",
        "microsoft.com",
        "twitch.tv",
        "canva.com",
        "vk.com",
        "weather.com",
        "fandom.com",
        "duckduckgo.com",
        "zoom.us",
        "nytimes.com",
        "ebay.com",
        "espn.com",
        "roblox.com",
        "discord.com",
        "spotify.com",
        "apple.com",
        "bbc.co.uk",
        "booking.com",
        "walmart.com",
        "github.com",
        "etsy.com",
        "telegram.org",
        "imdb.com",
        "deepseek.com",
        "openai.com",
        "shein.com",
        "disneyplus.com",
        "perplexity.ai",
    ],
}


# Verification: ensure all years have exactly 50 domains
def verify():
    """Verify data integrity of the DOMAINS_BY_YEAR dictionary."""
    errors = []
    for year in range(2000, 2026):
        if year not in DOMAINS_BY_YEAR:
            errors.append(f"Missing year: {year}")
            continue
        count = len(DOMAINS_BY_YEAR[year])
        if count != 50:
            errors.append(f"Year {year}: has {count} domains (expected 50)")
        # Check for duplicates within a year
        dupes = [d for d in DOMAINS_BY_YEAR[year]
                 if DOMAINS_BY_YEAR[year].count(d) > 1]
        if dupes:
            errors.append(f"Year {year}: duplicate domains: {set(dupes)}")
    if errors:
        for e in errors:
            print(f"  ERROR: {e}")
        return False
    print(f"  All {len(DOMAINS_BY_YEAR)} years verified: 50 unique domains each.")
    return True


if __name__ == "__main__":
    verify()

    # Print summary statistics
    all_domains = set()
    for year, domains in DOMAINS_BY_YEAR.items():
        all_domains.update(domains)
    print(f"  Total unique domains across all years: {len(all_domains)}")

    # Show domains that appear in early years but not in later years (potentially defunct)
    early_only = set()
    for year in range(2000, 2010):
        early_only.update(DOMAINS_BY_YEAR[year])
    late = set()
    for year in range(2020, 2026):
        late.update(DOMAINS_BY_YEAR[year])
    defunct_candidates = early_only - late
    print(f"  Domains popular pre-2010 but absent post-2020: {len(defunct_candidates)}")
    print(f"  Examples: {sorted(defunct_candidates)[:20]}")
